<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <AssemblyName>LoadAssembliesOnStartup.Fody.TestAssemblyToReferenceWithIgnores</AssemblyName>
    <RootNamespace>LoadAssembliesOnStartup.Fody.TestAssemblyToReferenceWithIgnores</RootNamespace>
    <DefaultLanguage>en-US</DefaultLanguage>
    <PackageId>LoadAssembliesOnStartup.Fody.TestAssemblyToReferenceWithIgnores</PackageId>
    <PackageVersion>1.0.0-alpha0001</PackageVersion>
    <Description>LoadAssembliesOnStartup.Fody.TestAssemblyToReferenceWithIgnores library.</Description>
    <PackageTags></PackageTags>
    <SonarQubeExclude>true</SonarQubeExclude>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Catel.Core" />
    <PackageReference Include="ModuleInit.Fody" PrivateAssets="All" />
  </ItemGroup>
  
  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props" Condition="Exists('$(MSBuildProjectDirectory)\..\Directory.Build.shared.explicit.props')" />
  <Import Project="$(MSBuildProjectDirectory)\..\Directory.Build.shared.mat.props" Condition="Exists('$(MSBuildProjectDirectory)\..\Directory.Build.shared.mat.props')" />
</Project>