//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("CatenaLogic")]
[assembly: AssemblyVersion("3.0.5")]
[assembly: AssemblyFileVersion("3.0.5")]
[assembly: AssemblyInformationalVersion("3.0.5-beta.1+1")]
[assembly: AssemblyCopyright("Copyright © Fody 2015 - 2019")]

